name: Deploy de mis practicas JS
on:
    push:
      branches:
        - main
jobs:
  deploy-exercise:
    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout
        uses: actions/checkout@v2.3.1

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .